import type { QuestionType } from "./types";

/**
 * 체험 모드에서 사용하는 초급 문제 은행입니다. 실제 백엔드가 연결되면
 * 공개 Question 응답에는 정답을 포함하지 않고 서버가 채점합니다.
 * 현재 체험 모드는 브라우저 안에서 동작하므로 정답 데이터도 번들에 포함됩니다.
 */
export type DemoTopicCode = "ANIMAL" | "FOOD" | "DAILY_LIFE";

export type DemoQuestionSeed = {
  topic: DemoTopicCode;
  type: QuestionType;
  questionText: string;
  questionTextKo: string;
  imageUrl: string;
  modelAnswer: string;
  acceptedAnswers: string[];
  hintText: string;
};

export const DEMO_ASSET_BASE_URL =
  "https://malhaebom-assets-prod-514090179227-ap-northeast-2-an.s3.ap-northeast-2.amazonaws.com";

export function demoAssetUrl(path: string) {
  return `${DEMO_ASSET_BASE_URL}${path}`;
}

export const DEMO_QUESTION_BANK: DemoQuestionSeed[] = [
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/cat.webp", modelAnswer: "It is a cat.", acceptedAnswers: ["cat", "a cat", "It's a cat.", "It is a kitty.", "kitty"], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/dog.webp", modelAnswer: "It is a dog.", acceptedAnswers: ["dog", "a dog", "It's a dog.", "It is a puppy.", "puppy"], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/rabbit.webp", modelAnswer: "It is a rabbit.", acceptedAnswers: ["rabbit", "a rabbit", "It's a rabbit.", "It is a bunny.", "bunny"], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/elephant.webp", modelAnswer: "It is an elephant.", acceptedAnswers: ["elephant", "an elephant", "It's an elephant."], hintText: "It is an ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/lion.webp", modelAnswer: "It is a lion.", acceptedAnswers: ["lion", "a lion", "It's a lion."], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/monkey.webp", modelAnswer: "It is a monkey.", acceptedAnswers: ["monkey", "a monkey", "It's a monkey."], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/bird.webp", modelAnswer: "It is a bird.", acceptedAnswers: ["bird", "a bird", "It's a bird."], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/fish.webp", modelAnswer: "It is a fish.", acceptedAnswers: ["fish", "a fish", "It's a fish."], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/duck.webp", modelAnswer: "It is a duck.", acceptedAnswers: ["duck", "a duck", "It's a duck.", "It is a duckling.", "duckling"], hintText: "It is a ___." },
  { topic: "ANIMAL", type: "SHORT_ANSWER", questionText: "What animal is this?", questionTextKo: "이 동물은 무엇일까요?", imageUrl: "/question-images/easy/animal/short-answer/bear.webp", modelAnswer: "It is a bear.", acceptedAnswers: ["bear", "a bear", "It's a bear."], hintText: "It is a ___." },

  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "What is the cat doing?", questionTextKo: "고양이는 무엇을 하고 있나요?", imageUrl: "/question-images/easy/animal/picture-description/cat-sleeping.webp", modelAnswer: "The cat is sleeping.", acceptedAnswers: ["It is sleeping.", "The cat sleeps.", "Sleeping"], hintText: "The cat is ___." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "What is the dog doing?", questionTextKo: "강아지는 무엇을 하고 있나요?", imageUrl: "/question-images/easy/animal/picture-description/dog-running.webp", modelAnswer: "The dog is running.", acceptedAnswers: ["It is running.", "The dog runs.", "Running"], hintText: "The dog is ___." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "Where is the rabbit?", questionTextKo: "토끼는 어디에 있나요?", imageUrl: "/question-images/easy/animal/picture-description/rabbit-under-table.webp", modelAnswer: "The rabbit is under the table.", acceptedAnswers: ["It is under the table.", "Under the table", "The bunny is under the table."], hintText: "The rabbit is ___ the table." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "Is the elephant big?", questionTextKo: "코끼리는 큰가요?", imageUrl: "/question-images/easy/animal/picture-description/big-elephant.webp", modelAnswer: "Yes, it is big.", acceptedAnswers: ["Yes.", "Yes, it is.", "The elephant is big.", "It is big."], hintText: "Yes, it is ___." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "What is the monkey eating?", questionTextKo: "원숭이는 무엇을 먹고 있나요?", imageUrl: "/question-images/easy/animal/picture-description/monkey-eating-banana.webp", modelAnswer: "The monkey is eating a banana.", acceptedAnswers: ["A banana", "Banana", "It is eating a banana.", "The monkey eats a banana."], hintText: "The monkey is eating a ___." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "What can the bird do?", questionTextKo: "새는 무엇을 할 수 있나요?", imageUrl: "/question-images/easy/animal/picture-description/bird-flying.webp", modelAnswer: "The bird can fly.", acceptedAnswers: ["It can fly.", "A bird can fly.", "Fly", "It is flying."], hintText: "The bird can ___." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "Where is the fish?", questionTextKo: "물고기는 어디에 있나요?", imageUrl: "/question-images/easy/animal/picture-description/fish-in-water.webp", modelAnswer: "The fish is in the water.", acceptedAnswers: ["It is in the water.", "In the water", "The fish is underwater."], hintText: "The fish is in the ___." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "How many ducks are there?", questionTextKo: "오리는 몇 마리 있나요?", imageUrl: "/question-images/easy/animal/picture-description/three-ducks.webp", modelAnswer: "There are three ducks.", acceptedAnswers: ["Three", "Three ducks", "There are three.", "I see three ducks."], hintText: "There are ___ ducks." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "What color is the bear?", questionTextKo: "곰은 무슨 색인가요?", imageUrl: "/question-images/easy/animal/picture-description/brown-bear.webp", modelAnswer: "The bear is brown.", acceptedAnswers: ["Brown", "It is brown.", "The bear's color is brown."], hintText: "The bear is ___." },
  { topic: "ANIMAL", type: "PICTURE_DESCRIPTION", questionText: "Is the lion sleeping?", questionTextKo: "사자는 자고 있나요?", imageUrl: "/question-images/easy/animal/picture-description/lion-awake.webp", modelAnswer: "No, it is not.", acceptedAnswers: ["No.", "No, it's not.", "No, the lion is awake.", "The lion is not sleeping."], hintText: "No, it is ___." },

  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "What animal do you like?", questionTextKo: "어떤 동물을 좋아하나요?", imageUrl: "/question-images/easy/animal/open-speaking/favorite-animal-choices.webp", modelAnswer: "I like cats.", acceptedAnswers: ["I like cat.", "I like dogs.", "I like rabbits.", "I like birds."], hintText: "I like ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "What pet do you want?", questionTextKo: "어떤 반려동물을 키우고 싶나요?", imageUrl: "/question-images/easy/animal/open-speaking/pet-choices.webp", modelAnswer: "I want a dog.", acceptedAnswers: ["I want a cat.", "I want a rabbit.", "I want a bird.", "A dog"], hintText: "I want a ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "Which zoo animal do you want to see?", questionTextKo: "동물원에서 어떤 동물을 보고 싶나요?", imageUrl: "/question-images/easy/animal/open-speaking/zoo-animal-choices.webp", modelAnswer: "I want to see the lion.", acceptedAnswers: ["I want to see a lion.", "I want to see the elephant.", "I want to see the monkey.", "I want to see the bear."], hintText: "I want to see the ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "What can you do with your dog?", questionTextKo: "강아지와 무엇을 할 수 있나요?", imageUrl: "/question-images/easy/animal/open-speaking/play-with-dog.webp", modelAnswer: "I can play with my dog.", acceptedAnswers: ["I can walk my dog.", "I can run with my dog.", "I can pet my dog.", "I play with my dog."], hintText: "I can ___ with my dog." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "What can you give the hungry rabbit?", questionTextKo: "배고픈 토끼에게 무엇을 줄 수 있나요?", imageUrl: "/question-images/easy/animal/open-speaking/feed-hungry-rabbit.webp", modelAnswer: "I can give it a carrot.", acceptedAnswers: ["A carrot", "I can give it lettuce.", "I can give it an apple.", "I can give it water."], hintText: "I can give it ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "Where do you want to watch birds?", questionTextKo: "어디에서 새를 보고 싶나요?", imageUrl: "/question-images/easy/animal/open-speaking/watch-birds.webp", modelAnswer: "I want to watch birds in the park.", acceptedAnswers: ["In the park", "I want to watch them in the forest.", "I want to watch birds at the zoo.", "I want to watch birds in the garden."], hintText: "I want to watch birds in the ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "How can you help this small cat?", questionTextKo: "이 작은 고양이를 어떻게 도와줄 수 있나요?", imageUrl: "/question-images/easy/animal/open-speaking/help-small-cat.webp", modelAnswer: "I can give the cat some food.", acceptedAnswers: ["I can give it food.", "I can give it water.", "I can take it home.", "I can pet the cat."], hintText: "I can give the cat ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "What animal do you want to draw?", questionTextKo: "어떤 동물을 그리고 싶나요?", imageUrl: "/question-images/easy/animal/open-speaking/draw-animal-choices.webp", modelAnswer: "I want to draw a rabbit.", acceptedAnswers: ["I want to draw a cat.", "I want to draw a dog.", "I want to draw a lion.", "A rabbit"], hintText: "I want to draw a ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "What name do you want to give this puppy?", questionTextKo: "이 강아지에게 어떤 이름을 지어 주고 싶나요?", imageUrl: "/question-images/easy/animal/open-speaking/name-puppy.webp", modelAnswer: "I want to name it Coco.", acceptedAnswers: ["Its name is Coco.", "I want to name it Max.", "I want to name it Happy.", "I want to name it Lucky."], hintText: "I want to name it ___." },
  { topic: "ANIMAL", type: "OPEN_SPEAKING", questionText: "How do you feel today?", questionTextKo: "오늘 기분이 어떤가요?", imageUrl: "/question-images/easy/animal/open-speaking/animal-feelings.webp", modelAnswer: "I feel happy.", acceptedAnswers: ["I am happy.", "I feel sleepy.", "I feel excited.", "I feel tired."], hintText: "I feel ___." },

  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What food is this?", questionTextKo: "이 음식은 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/apple.webp", modelAnswer: "It is an apple.", acceptedAnswers: ["apple", "an apple", "It's an apple."], hintText: "It is an ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What food is this?", questionTextKo: "이 음식은 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/banana.webp", modelAnswer: "It is a banana.", acceptedAnswers: ["banana", "a banana", "It's a banana."], hintText: "It is a ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What fruit is this?", questionTextKo: "이 과일은 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/orange.webp", modelAnswer: "It is an orange.", acceptedAnswers: ["orange", "an orange", "It's an orange."], hintText: "It is an ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What fruit is this?", questionTextKo: "이 과일은 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/strawberry.webp", modelAnswer: "It is a strawberry.", acceptedAnswers: ["strawberry", "a strawberry", "It's a strawberry."], hintText: "It is a ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What drink is this?", questionTextKo: "이 음료는 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/milk.webp", modelAnswer: "It is milk.", acceptedAnswers: ["milk", "It's milk.", "a glass of milk", "It is a glass of milk."], hintText: "It is ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What food is this?", questionTextKo: "이 음식은 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/bread.webp", modelAnswer: "It is bread.", acceptedAnswers: ["bread", "It's bread.", "a loaf of bread", "It is a loaf of bread."], hintText: "It is ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What food is this?", questionTextKo: "이 음식은 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/egg.webp", modelAnswer: "It is an egg.", acceptedAnswers: ["egg", "an egg", "It's an egg."], hintText: "It is an ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What food is this?", questionTextKo: "이 음식은 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/pizza.webp", modelAnswer: "It is pizza.", acceptedAnswers: ["pizza", "It's pizza.", "a pizza", "It is a pizza."], hintText: "It is ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What vegetable is this?", questionTextKo: "이 채소는 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/carrot.webp", modelAnswer: "It is a carrot.", acceptedAnswers: ["carrot", "a carrot", "It's a carrot."], hintText: "It is a ___." },
  { topic: "FOOD", type: "SHORT_ANSWER", questionText: "What dessert is this?", questionTextKo: "이 디저트는 무엇일까요?", imageUrl: "/question-images/easy/food/short-answer/ice-cream.webp", modelAnswer: "It is ice cream.", acceptedAnswers: ["ice cream", "It's ice cream.", "an ice cream cone", "It is an ice cream cone."], hintText: "It is ___ ___." },

  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "What color is the apple?", questionTextKo: "사과는 무슨 색인가요?", imageUrl: "/question-images/easy/food/picture-description/red-apple.webp", modelAnswer: "The apple is red.", acceptedAnswers: ["Red", "It is red.", "It's red."], hintText: "The apple is ___." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "How many bananas are there?", questionTextKo: "바나나는 몇 개 있나요?", imageUrl: "/question-images/easy/food/picture-description/two-bananas.webp", modelAnswer: "There are two bananas.", acceptedAnswers: ["Two", "Two bananas", "There are two.", "I see two bananas."], hintText: "There are ___ bananas." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "What is the girl drinking?", questionTextKo: "여자아이는 무엇을 마시고 있나요?", imageUrl: "/question-images/easy/food/picture-description/girl-drinking-milk.webp", modelAnswer: "She is drinking milk.", acceptedAnswers: ["Milk", "She drinks milk.", "The girl is drinking milk.", "It is milk."], hintText: "She is drinking ___." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "Is the pizza round?", questionTextKo: "피자는 둥근 모양인가요?", imageUrl: "/question-images/easy/food/picture-description/round-pizza.webp", modelAnswer: "Yes, it is round.", acceptedAnswers: ["Yes.", "Yes, it is.", "The pizza is round.", "It is round."], hintText: "Yes, it is ___." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "Where is the egg?", questionTextKo: "달걀은 어디에 있나요?", imageUrl: "/question-images/easy/food/picture-description/egg-on-plate.webp", modelAnswer: "The egg is on the plate.", acceptedAnswers: ["On the plate", "It is on the plate.", "The egg is on a plate."], hintText: "The egg is on the ___." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "What is in the sandwich?", questionTextKo: "샌드위치 안에는 무엇이 있나요?", imageUrl: "/question-images/easy/food/picture-description/cheese-sandwich.webp", modelAnswer: "There is cheese in the sandwich.", acceptedAnswers: ["Cheese", "It has cheese.", "Cheese is in the sandwich.", "The sandwich has cheese."], hintText: "There is ___ in the sandwich." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "Is the soup hot?", questionTextKo: "수프는 뜨거운가요?", imageUrl: "/question-images/easy/food/picture-description/hot-soup.webp", modelAnswer: "Yes, the soup is hot.", acceptedAnswers: ["Yes.", "Yes, it is.", "It is hot.", "The soup is hot."], hintText: "Yes, the soup is ___." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "What is the boy eating?", questionTextKo: "남자아이는 무엇을 먹고 있나요?", imageUrl: "/question-images/easy/food/picture-description/boy-eating-ice-cream.webp", modelAnswer: "He is eating ice cream.", acceptedAnswers: ["Ice cream", "He eats ice cream.", "The boy is eating ice cream."], hintText: "He is eating ___ ___." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "Which carrot is longer?", questionTextKo: "어느 당근이 더 긴가요?", imageUrl: "/question-images/easy/food/picture-description/long-orange-carrot.webp", modelAnswer: "The orange carrot is longer.", acceptedAnswers: ["The orange one", "The orange carrot", "Orange", "This carrot is longer."], hintText: "The ___ carrot is longer." },
  { topic: "FOOD", type: "PICTURE_DESCRIPTION", questionText: "Are the strawberries sweet?", questionTextKo: "딸기는 달콤한가요?", imageUrl: "/question-images/easy/food/picture-description/sweet-strawberries.webp", modelAnswer: "Yes, they are sweet.", acceptedAnswers: ["Yes.", "Yes, they are.", "The strawberries are sweet.", "They are sweet."], hintText: "Yes, they are ___." },

  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What fruit do you like?", questionTextKo: "어떤 과일을 좋아하나요?", imageUrl: "/question-images/easy/food/open-speaking/favorite-fruit-choices.webp", modelAnswer: "I like apples.", acceptedAnswers: ["I like apples.", "I like bananas.", "I like oranges.", "I like strawberries."], hintText: "I like ___." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What do you eat for breakfast?", questionTextKo: "아침으로 무엇을 먹나요?", imageUrl: "/question-images/easy/food/open-speaking/breakfast-choices.webp", modelAnswer: "I eat eggs for breakfast.", acceptedAnswers: ["I eat eggs for breakfast.", "I eat bread for breakfast.", "I eat cereal for breakfast.", "I eat rice for breakfast."], hintText: "I eat ___ for breakfast." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What do you drink when you are thirsty?", questionTextKo: "목이 마를 때 무엇을 마시나요?", imageUrl: "/question-images/easy/food/open-speaking/thirsty-drink-choices.webp", modelAnswer: "I drink water.", acceptedAnswers: ["I drink water.", "I drink milk.", "I drink juice.", "I drink tea."], hintText: "I drink ___." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "When do you eat apples?", questionTextKo: "언제 사과를 먹나요?", imageUrl: "/question-images/easy/food/open-speaking/eat-apples-time.webp", modelAnswer: "I eat apples after lunch.", acceptedAnswers: ["I eat apples after lunch.", "I eat apples in the morning.", "I eat apples after school.", "I eat apples at snack time."], hintText: "I eat apples ___." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What snack do you want?", questionTextKo: "어떤 간식을 먹고 싶나요?", imageUrl: "/question-images/easy/food/open-speaking/snack-choices.webp", modelAnswer: "I want a banana.", acceptedAnswers: ["I want a banana.", "I want an apple.", "I want some cookies.", "I want yogurt."], hintText: "I want ___." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What food can you share with a friend?", questionTextKo: "친구와 어떤 음식을 나눠 먹을 수 있나요?", imageUrl: "/question-images/easy/food/open-speaking/share-food.webp", modelAnswer: "I can share my pizza.", acceptedAnswers: ["I can share my pizza.", "I can share my cookies.", "I can share an apple.", "I can share my bread."], hintText: "I can share ___." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "Which healthy food do you want?", questionTextKo: "어떤 건강한 음식을 고르겠나요?", imageUrl: "/question-images/easy/food/open-speaking/healthy-food-choices.webp", modelAnswer: "I want the carrots.", acceptedAnswers: ["I want the carrots.", "I want the apple.", "I want the salad.", "I want the fruit."], hintText: "I want ___." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What ice cream flavor do you like?", questionTextKo: "어떤 맛의 아이스크림을 좋아하나요?", imageUrl: "/question-images/easy/food/open-speaking/ice-cream-flavors.webp", modelAnswer: "I like chocolate ice cream.", acceptedAnswers: ["I like chocolate ice cream.", "I like vanilla ice cream.", "I like strawberry ice cream.", "I like mint ice cream."], hintText: "I like ___ ice cream." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What do you want in your sandwich?", questionTextKo: "샌드위치에 무엇을 넣고 싶나요?", imageUrl: "/question-images/easy/food/open-speaking/sandwich-fillings.webp", modelAnswer: "I want cheese in it.", acceptedAnswers: ["I want cheese in it.", "I want an egg in it.", "I want ham in it.", "I want lettuce in it."], hintText: "I want ___ in it." },
  { topic: "FOOD", type: "OPEN_SPEAKING", questionText: "What food do you want to take on a picnic?", questionTextKo: "소풍에 어떤 음식을 가져가고 싶나요?", imageUrl: "/question-images/easy/food/open-speaking/picnic-food.webp", modelAnswer: "I want to take sandwiches.", acceptedAnswers: ["I want to take sandwiches.", "I want to take fruit.", "I want to take apples.", "I want to take cookies."], hintText: "I want to take ___." },

  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/toothbrush.webp", modelAnswer: "It is a toothbrush.", acceptedAnswers: ["toothbrush", "a toothbrush", "It's a toothbrush."], hintText: "It is a ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/school-bag.webp", modelAnswer: "It is a school bag.", acceptedAnswers: ["school bag", "a school bag", "It's a school bag.", "backpack", "a backpack"], hintText: "It is a school ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/book.webp", modelAnswer: "It is a book.", acceptedAnswers: ["book", "a book", "It's a book."], hintText: "It is a ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/pencil.webp", modelAnswer: "It is a pencil.", acceptedAnswers: ["pencil", "a pencil", "It's a pencil."], hintText: "It is a ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/bed.webp", modelAnswer: "It is a bed.", acceptedAnswers: ["bed", "a bed", "It's a bed."], hintText: "It is a ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/clock.webp", modelAnswer: "It is a clock.", acceptedAnswers: ["clock", "a clock", "It's a clock."], hintText: "It is a ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/umbrella.webp", modelAnswer: "It is an umbrella.", acceptedAnswers: ["umbrella", "an umbrella", "It's an umbrella."], hintText: "It is an ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What are these?", questionTextKo: "이것들은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/shoes.webp", modelAnswer: "They are shoes.", acceptedAnswers: ["shoes", "They are my shoes.", "a pair of shoes", "It's a pair of shoes."], hintText: "They are ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/bus.webp", modelAnswer: "It is a bus.", acceptedAnswers: ["bus", "a bus", "It's a bus.", "school bus", "a school bus"], hintText: "It is a ___." },
  { topic: "DAILY_LIFE", type: "SHORT_ANSWER", questionText: "What is this?", questionTextKo: "이것은 무엇일까요?", imageUrl: "/question-images/easy/daily-life/short-answer/ball.webp", modelAnswer: "It is a ball.", acceptedAnswers: ["ball", "a ball", "It's a ball."], hintText: "It is a ___." },

  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "What is the boy doing?", questionTextKo: "남자아이는 무엇을 하고 있나요?", imageUrl: "/question-images/easy/daily-life/picture-description/boy-brushing-teeth.webp", modelAnswer: "He is brushing his teeth.", acceptedAnswers: ["The boy is brushing his teeth.", "He brushes his teeth.", "Brushing his teeth"], hintText: "He is brushing his ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "What is the girl doing?", questionTextKo: "여자아이는 무엇을 하고 있나요?", imageUrl: "/question-images/easy/daily-life/picture-description/girl-reading-book.webp", modelAnswer: "She is reading a book.", acceptedAnswers: ["The girl is reading a book.", "She reads a book.", "Reading a book"], hintText: "She is reading a ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "Where is the pencil?", questionTextKo: "연필은 어디에 있나요?", imageUrl: "/question-images/easy/daily-life/picture-description/pencil-on-desk.webp", modelAnswer: "The pencil is on the desk.", acceptedAnswers: ["On the desk", "It is on the desk.", "The pencil is on a desk."], hintText: "The pencil is on the ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "How does the boy go to school?", questionTextKo: "남자아이는 학교에 어떻게 가나요?", imageUrl: "/question-images/easy/daily-life/picture-description/boy-riding-school-bus.webp", modelAnswer: "He goes to school by bus.", acceptedAnswers: ["By bus", "He takes the bus.", "He rides the bus.", "The boy goes by bus."], hintText: "He goes to school by ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "What is the mother doing?", questionTextKo: "엄마는 무엇을 하고 있나요?", imageUrl: "/question-images/easy/daily-life/picture-description/mother-cooking.webp", modelAnswer: "She is cooking dinner.", acceptedAnswers: ["She is cooking.", "The mother is cooking.", "She cooks dinner.", "Cooking dinner"], hintText: "She is cooking ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "Is the child sleeping?", questionTextKo: "아이는 자고 있나요?", imageUrl: "/question-images/easy/daily-life/picture-description/child-sleeping.webp", modelAnswer: "Yes, the child is sleeping.", acceptedAnswers: ["Yes.", "Yes, the child is.", "Yes, the child is asleep.", "The child is sleeping."], hintText: "Yes, the child is ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "What is the weather like?", questionTextKo: "날씨가 어떤가요?", imageUrl: "/question-images/easy/daily-life/picture-description/rainy-day.webp", modelAnswer: "It is rainy.", acceptedAnswers: ["Rainy", "It's rainy.", "It is raining.", "The weather is rainy."], hintText: "It is ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "What are the children doing?", questionTextKo: "아이들은 무엇을 하고 있나요?", imageUrl: "/question-images/easy/daily-life/picture-description/children-playing-ball.webp", modelAnswer: "They are playing with a ball.", acceptedAnswers: ["The children are playing ball.", "They play with a ball.", "Playing with a ball", "They are playing."], hintText: "They are playing with a ___." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "What time is it?", questionTextKo: "몇 시인가요?", imageUrl: "/question-images/easy/daily-life/picture-description/clock-seven.webp", modelAnswer: "It is seven o'clock.", acceptedAnswers: ["Seven", "Seven o'clock", "It's seven.", "It is seven."], hintText: "It is ___ o'clock." },
  { topic: "DAILY_LIFE", type: "PICTURE_DESCRIPTION", questionText: "Is the room clean?", questionTextKo: "방이 깨끗한가요?", imageUrl: "/question-images/easy/daily-life/picture-description/clean-room.webp", modelAnswer: "Yes, the room is clean.", acceptedAnswers: ["Yes.", "Yes, it is.", "It is clean.", "The room is clean."], hintText: "Yes, the room is ___." },

  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What do you do in the morning?", questionTextKo: "아침에 무엇을 하나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/morning-routine.webp", modelAnswer: "I brush my teeth.", acceptedAnswers: ["I brush my teeth.", "I wash my face.", "I eat breakfast.", "I get dressed."], hintText: "I ___ in the morning." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "How do you go to school?", questionTextKo: "학교에 어떻게 가나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/go-to-school.webp", modelAnswer: "I go to school by bus.", acceptedAnswers: ["I go to school by bus.", "I walk to school.", "I go to school by car.", "I ride my bike to school."], hintText: "I go to school by ___." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What do you do after school?", questionTextKo: "학교가 끝난 뒤 무엇을 하나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/after-school.webp", modelAnswer: "I play with my friends.", acceptedAnswers: ["I play with my friends.", "I do my homework.", "I go home.", "I read a book."], hintText: "I ___ after school." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What game do you like to play?", questionTextKo: "어떤 놀이를 좋아하나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/favorite-game.webp", modelAnswer: "I like to play soccer.", acceptedAnswers: ["I like to play soccer.", "I like to play tag.", "I like to play hide-and-seek.", "I like to play basketball."], hintText: "I like to play ___." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "How can you help at home?", questionTextKo: "집에서 어떻게 도울 수 있나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/help-at-home.webp", modelAnswer: "I can clean my room.", acceptedAnswers: ["I can clean my room.", "I can set the table.", "I can put away my toys.", "I can wash the dishes."], hintText: "I can ___." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What do you take on a rainy day?", questionTextKo: "비 오는 날에는 무엇을 가져가나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/rainy-day-items.webp", modelAnswer: "I take an umbrella.", acceptedAnswers: ["I take an umbrella.", "I take my raincoat.", "I take my rain boots.", "I take a rain hat."], hintText: "I take an ___." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What do you do before bed?", questionTextKo: "잠자기 전에 무엇을 하나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/bedtime-routine.webp", modelAnswer: "I read a book.", acceptedAnswers: ["I read a book.", "I brush my teeth.", "I put on my pajamas.", "I wash my face."], hintText: "I ___ before bed." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What do you do with your friend?", questionTextKo: "친구와 무엇을 하나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/with-friend.webp", modelAnswer: "I play with my friend.", acceptedAnswers: ["I play with my friend.", "I talk with my friend.", "I read with my friend.", "I share toys with my friend."], hintText: "I ___ with my friend." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What do you like in your classroom?", questionTextKo: "교실에서 무엇을 좋아하나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/classroom-favorites.webp", modelAnswer: "I like the books.", acceptedAnswers: ["I like the books.", "I like my desk.", "I like the pictures.", "I like my teacher."], hintText: "I like ___." },
  { topic: "DAILY_LIFE", type: "OPEN_SPEAKING", questionText: "What do you want to do this weekend?", questionTextKo: "이번 주말에 무엇을 하고 싶나요?", imageUrl: "/question-images/easy/daily-life/open-speaking/weekend-activities.webp", modelAnswer: "I want to go to the park.", acceptedAnswers: ["I want to go to the park.", "I want to ride my bike.", "I want to see my family.", "I want to read a book."], hintText: "I want to ___." },
];
